USE hr;
DELIMITER $$

CREATE TRIGGER addExFuncionarios
	AFTER DELETE ON employees
    FOR EACH ROW
BEGIN
	INSERT INTO exfuncionarios(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
    values (
		OLD.EMPLOYEE_ID, 
		OLD.FIRST_NAME, 
		OLD.LAST_NAME, 
		OLD.EMAIL, 
		OLD.PHONE_NUMBER, 
		OLD.HIRE_DATE, 
		OLD.JOB_ID, 
		OLD.SALARY, 
		OLD.COMMISSION_PCT, 
		OLD.MANAGER_ID, 
		OLD.DEPARTMENT_ID
	);
END $$

DELIMITER ;
